name: splitwise
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.1
  provider: ^6.1.2
  cloud_firestore: ^5.4.4
  sqflite: ^2.4.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  fl_chart: ^0.69.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  firebase_storage: ^12.3.3
  image_picker: ^1.1.2
  flutter_staggered_animations: ^1.1.1
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.13.0
  path: ^1.9.1
  google_sign_in: ^6.3.0
  cached_network_image: ^3.4.1

flutter_native_splash:
  color: "#F8F9FA"
  image: assets/logo/Logo.png
  color_dark: "#0D1B2A"
  image_dark: assets/logo/Logo.png

  android_12:
    image: assets/logo/Logo.png
    icon_background_color: "#F8F9FA"
    image_dark: assets/logo/Logo.png
    icon_background_color_dark: "#0D1B2A"

  ios: true
  fullscreen: true

  # Background image is only applicable for iOS
  ios_content_mode: center

  web: false

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/Logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo/Logo.png
    - assets/logo/icon.png
    - assets/images/
